# -*- coding: utf-8 -*-
"""NLP_Unit-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145ebVXWj1TfsTHnKwEK6ehUGt29tqboP
"""

# PROGRAM 1: Chatbot

import re
import random
from datetime import datetime

patterns = [
    (r'hello|hi|hey|good morning|good evening',
     ['Hello! How can I help you today?',
      'Hi there! What can I do for you?',
      'Hey! Nice to meet you. How can I assist?']),

    (r'how are you|how do you do|are you ok',
     ['I am doing great, thank you for asking!',
      'I am fine! Ready to assist you.',
      'All systems running perfectly! How about you?']),

    (r'what is your name|who are you|your name',
     ['I am ChatBot, your virtual assistant!',
      'My name is ChatBot. I am here to help you!']),

    (r'bye|goodbye|see you|take care',
     ['Goodbye! Have a wonderful day!',
      'Bye! Come back anytime.',
      'See you later! Take care!']),

    (r'thank you|thanks|thank u',
     ['You are welcome!',
      'Happy to help!',
      'Anytime! That is what I am here for.']),

    (r'weather|temperature|climate|forecast',
     ['I cannot check live weather, but try weather.com!',
      'For accurate forecast, please visit a weather site.']),

    (r'time|what time|current time',
     [f'Current time is: {datetime.now().strftime("%H:%M:%S")}',
      f'The time right now is {datetime.now().strftime("%I:%M %p")}']),

    (r'date|today|what day',
     [f'Today is {datetime.now().strftime("%A, %B %d, %Y")}']),

    (r'help|what can you do|features|capabilities',
     ['I can: answer greetings, tell time/date, '
      'chat with you, and respond to common questions!']),

    (r'joke|funny|make me laugh',
     ['Why do programmers prefer dark mode? Because light attracts bugs!',
      'Why did the computer go to the doctor? It had a virus!',
      'I told my computer I needed a break. Now it keeps sending me Kit-Kat ads!']),

    (r'age|how old are you|when were you created',
     ['I am ageless! I was created to assist you anytime.']),

    (r'who made you|who created you|developer',
     ['I was created as part of a Natural Language Processing assignment!']),
]

def chatbot_response(user_input):
    user_input = user_input.lower().strip()
    for pattern, responses in patterns:
        if re.search(pattern, user_input):
            return random.choice(responses)
    return ('I am not sure how to respond to that. '
            'Try asking about time, date, jokes, or just say hello!')

test_inputs = [
    'Hello there!',
    'How are you?',
    'What is your name?',
    'Tell me a joke',
    'What is the time?',
    'What is today date?',
    'What can you do?',
    'Who created you?',
    'Thank you so much!',
    'What is quantum physics?',
    'Bye!'
]

print('Chatbot')
for user_msg in test_inputs:
    response = chatbot_response(user_msg)
    print(f'User : {user_msg}')
    print(f'Bot  : {response}')
    print('-' * 55)

# PROGRAM 2: QUESTION ANSWERING using HuggingFace Transformers

!pip install transformers torch -q

from transformers import pipeline

print("Loading Question Answering model...")
qa_pipeline = pipeline(
    "question-answering",
    model="deepset/roberta-base-squad2"
)
print("Model loaded successfully!\n")

context1 = """
Machine Learning is a subset of artificial intelligence that enables systems
to learn from data and improve performance without being explicitly programmed.
It was popularized by Arthur Samuel in 1959. Applications include recommendation
systems, fraud detection, and image recognition. Machine learning uses algorithms
to identify patterns in data.
"""

context2 = """
Cloud computing is the delivery of computing services such as storage,
servers, and databases over the internet. Major providers include Amazon Web Services,
Microsoft Azure, and Google Cloud. It offers scalability, flexibility,
and cost efficiency. Cloud computing allows users to access services remotely.
"""

context3 = """
The human brain is the central organ of the nervous system.
It controls thoughts, memory, emotion, and motor skills.
The brain consists of different parts including the cerebrum,
cerebellum, and brainstem. It processes information received
from the body and coordinates responses.
"""

# --- Questions ---
qa_pairs = [
    (context1, 'What is machine learning?'),
    (context1, 'Who popularized machine learning?'),
    (context1, 'What are applications of machine learning?'),

    (context2, 'What is cloud computing?'),
    (context2, 'Name some cloud providers'),
    (context2, 'What are benefits of cloud computing?'),

    (context3, 'What does the brain control?'),
    (context3, 'What are parts of the brain?'),
    (context3, 'What is the function of the brain?'),
]

print('=' * 62)
print('          QUESTION ANSWERING RESULTS')
print('=' * 62)
for i, (ctx, question) in enumerate(qa_pairs, 1):
    result = qa_pipeline(question=question, context=ctx)
    print(f'Q{i}: {question}')
    print(f'    Answer : {result["answer"]}')
    print(f'    Score  : {result["score"]:.4f}')
    print('-' * 62)

# PROGRAM 3: TEXT SUMMARIZATION


import re
from collections import Counter

def extractive_summarize(text, num_sentences=2):
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    sentences = [s.strip() for s in sentences if len(s.split()) > 4]

    stopwords = {'the','a','an','is','are','was','were','in','on','at',
                 'to','of','and','or','but','it','its','this','that',
                 'with','for','from','by','as','be','been','have','has',
                 'had','will','would','could','should','may','might','do',
                 'does','did','not','no','so','if','than','then','when',
                 'while','after','before','since','about','into','through',
                 'during','including','without','also','their','they','them',
                 'these','those','which','who','whom','what','how','more'}

    words = re.findall(r'\b[a-z]+\b', text.lower())
    word_freq = Counter(w for w in words if w not in stopwords)

    def score_sentence(sent):
        words_in_sent = re.findall(r'\b[a-z]+\b', sent.lower())
        return sum(word_freq.get(w, 0) for w in words_in_sent if w not in stopwords)

    scored = [(score_sentence(s), i, s) for i, s in enumerate(sentences)]
    scored.sort(reverse=True)

    top = sorted(scored[:num_sentences], key=lambda x: x[1])
    return ' '.join(s for _, _, s in top)


# -------- NEW TEXTS --------
texts = [
    {
        'title': 'Cybersecurity',
        'text': (
            "Cybersecurity is the practice of protecting systems, networks, and data from cyber threats. "
            "Organizations implement firewalls, encryption, and authentication mechanisms to secure sensitive information. "
            "Cyber attacks such as phishing, malware, and ransomware have become increasingly sophisticated. "
            "Companies invest heavily in cybersecurity to prevent financial loss and data breaches. "
            "Awareness and regular updates are crucial to maintaining strong security systems."
        )
    },
    {
        'title': 'Blockchain Technology',
        'text': (
            "Blockchain is a distributed ledger technology that ensures transparency and security in data transactions. "
            "Each block contains a record of transactions and is linked to the previous one, forming a chain. "
            "It is widely used in cryptocurrencies like Bitcoin and Ethereum. "
            "Blockchain eliminates the need for intermediaries and enhances trust between parties. "
            "It has potential applications in finance, healthcare, and supply chain management."
        )
    },
    {
        'title': 'Internet of Things (IoT)',
        'text': (
            "The Internet of Things refers to a network of connected devices that communicate over the internet. "
            "Devices such as smart homes, wearable gadgets, and industrial sensors collect and share data. "
            "IoT improves efficiency and automation in various industries. "
            "However, it also raises concerns about data privacy and security. "
            "The growth of IoT is expected to transform daily life and business operations."
        )
    },
    {
        'title': 'E-Commerce',
        'text': (
            "E-commerce refers to buying and selling goods and services over the internet. "
            "Popular platforms like Amazon and Flipkart have revolutionized online shopping. "
            "Customers can browse products, compare prices, and make purchases from anywhere. "
            "Secure payment gateways and fast delivery services have boosted customer confidence. "
            "E-commerce continues to grow rapidly with advancements in technology."
        )
    },
]

# -------- OUTPUT --------
print('EXTRACTIVE TEXT SUMMARIZATION RESULTS')

for item in texts:
    summary = extractive_summarize(item['text'], num_sentences=2)
    original_words = len(item['text'].split())
    summary_words  = len(summary.split())
    reduction      = round((1 - summary_words / original_words) * 100, 1)

    print(f"\nTopic     : {item['title']}")
    print(f"Original  : {original_words} words")
    print(f"Summary   : {summary_words} words  ({reduction}% reduction)")
    print(f"Output    : {summary}")
    print('-' * 70)

print("\nSummarization complete!")

# PROGRAM 4: MACHINE TRANSLATION


from transformers import MarianMTModel, MarianTokenizer
def load_translator(model_name):
    print(f"Loading {model_name}...")
    tokenizer = MarianTokenizer.from_pretrained(model_name)
    model     = MarianMTModel.from_pretrained(model_name)
    return tokenizer, model

def translate(text, tokenizer, model):
    tokens = tokenizer([text], return_tensors="pt", padding=True)
    output = model.generate(**tokens)
    return tokenizer.decode(output[0], skip_special_tokens=True)

print("Loading translation models...\n")

tok_fr, mdl_fr = load_translator("Helsinki-NLP/opus-mt-en-fr")
tok_de, mdl_de = load_translator("Helsinki-NLP/opus-mt-en-de")
tok_es, mdl_es = load_translator("Helsinki-NLP/opus-mt-en-es")

print("\nAll models loaded!\n")

sentences = [
    "Data science is an interdisciplinary field that uses data to extract insights.",
    "Cybersecurity protects systems from digital attacks.",
    "The internet connects millions of devices worldwide.",
    "Cloud computing allows access to resources over the internet.",
    "Programming requires logical thinking and problem solving skills.",
    "Artificial intelligence is transforming industries globally.",
    "Learning new technologies helps in career growth.",
]

print('             MACHINE TRANSLATION RESULTS')


for sent in sentences:
    fr = translate(sent, tok_fr, mdl_fr)
    de = translate(sent, tok_de, mdl_de)
    es = translate(sent, tok_es, mdl_es)

    print(f"\nEN: {sent}")
    print(f"FR: {fr}")
    print(f"DE: {de}")
    print(f"ES: {es}")
    print('-' * 70)

print("\nTranslation complete!")